### ISSUE TITLE
Have py_session return a string rather than embed print statements.

### ISSUE THREAD

**Issue by darindf** [fbrundu/py_session#1]
It would be nice if the py_session function returned a string, so that it can be used with loggers, or saved/displayed via another means, rather than stdout.

**Comment by fbrundu** [comment]
Sounds like a good idea.
At the moment (undocumented) there's the parameter `return_list` which returns the list of modules. Internally, the list is used to print the modules. This should suffice your use case, but reopen this issue if you think a list of strings instead of a single string would me more useful for some use cases.
Thanks

**Comment by fbrundu** [comment]
I have updated the README accordingly.
